### PR TITLE
Allow formatting without decorative box using printBox parameter

### PR DESCRIPTION
**Pull request by IanWorthington**
I've modified the pretty printer to make the decorative box optional.

If this is of any use, please feel free to add it in to the base!

### CODE REVIEW

**Comment by IanWorthington** [comment]
This was reformatted with Android Studio 4.1.2.  Might your dartfmt give different output?

**Comment by haarts** [comment]
The dart formatter indeed gives a different output. `dart fmt` is the
formatter the project uses.

**Comment by IanWorthington** [comment]
> The dart formatter indeed gives a different output. `dart fmt` is the formatter the project uses.

Hi!  I'm sorry, but I'm rather confused.  According to https://dart.dev/tools/dart-format: 

> Use the dart format command to replace the whitespace in your program with formatting that follows Dart guidelines. This is the same formatting that you can get when using an IDE or editor that has Dart support.

What reformatter does this project use, and where can I get it from?

**Comment by IanWorthington** [comment]
Found a small error in FileOuput so I've pushed the fix for that as well.

It still fails the dartfmt test though and I've no idea how to fix that, sorry.  But if you let me know I'll do it.

**Comment by IanWorthington** [comment]
I don't know how to fix this and I need to push unrelated commits now, and as I have no idea of how to stop those being added to this PR I'm closing this.

Feel free to pull the code and use it if you wish.

**Pull request closed without merging**
