### PR TITLE
Fix the import issue for FileOutput class for mobile projects

### PR DESCRIPTION
**Pull request by HiDaN4**
- Use dart.io condition to fix the import for mobile flutter apps.

Seems like dart.library.io is an old example from Flutter team and is not working.
**if (dart.io)** condition works and properly imports the file for mobile apps

### CODE REVIEW

**Comment by haarts** [comment]
I agree, it seems `dart.io` is better. Would you care to rebase? Then I'll merge.

**Comment by HiDaN4** [comment]
Histories diverged since I originally forked your repo and made a branch from local master. Still, you should be able to merge without conflicts

**Comment by haarts** [comment]
I'll handle it. Thanks for you contribution!

**Comment by haarts** [comment]
close via 332be1c412a6212f7a24ef8edcf899c6feaa91d1

**Pull request closed without merging**
