### PR TITLE
[Feature] Add 'TAG' options

### PR DESCRIPTION
**Pull request by chejdj**
Add 'TAG' options

### CODE REVIEW

**Comment by haarts** [comment]
Thank you for your time contributing to this repo! 

Would your use case be served by this suggestion: https://github.com/leisim/logger/issues/68#issuecomment-786637080

**Comment by chejdj** [comment]
OK，but I think 'PrefixPrinter' is global. In fact, I only add some FLAGs for some modules.

**Comment by haarts** [comment]
The idea is to have a separate logger for each 'tag' or module.

**Comment by chejdj** [comment]
Thanks,  I misunderstand.

**Pull request closed without merging**
